#!/bin/bash

mount /dev/vg1/root /mnt
mount /dev/vg1/home /mnt/home
mount /dev/vg1/Files /mnt/Files
mount dev/nvme0n1p1 /mnt/boot

arch-chroot /mnt
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB 

blkid >> blk.txt
vim blkid.txt

find UUID of /dev/nvme0n1p2
type yy to cut and close vim

vim /etc/default/grub
p the UUID

vim /etc/default/grub
