#!/bin/bash

pacman -S grub efibootmgr networkmanager network-manager-applet wireless_tools wpa_supplicant dialog os-prober mtools dosfstools base-devel git bluez bluez-utils pulseaudio-bluetooth cups xdg-utils xdg-user-dirs openssh xorg i3-wm terminator firefox polybar rofi numlockx sxhkd 

#pacman -S acpi alsa-utils arandr i3-wm i3status autotilng bluedevil blueman bluetuith bluez bluez-hid2hci bluez-utils brightnessctl btop cairo cmake conky cups dialog dkms dosfstools efibootmgr engrampa exfat-utils expac feh firefox fuse2 fuse3 gedit gimp gnome-keyring gnome-mahjongg gufw gvfs gvfs-gphoto2 gvfs-smb haveged hplip ifuse imlib lib32-mesa libimobiledevice libreoffice libxnvctrl lutris lxappearance man-db man-pages mc mesa mpd mpv mtools ncdu neovim  ntfs-3g numlockx okular os-prober pacman-contrib pamixer pandoc-bin pavucontrol pavucontrol-qt pcmanfm picom playerctl polybar ponymix pulseaudio-bluetooth redshift ripgrep rofi rsync samba scrot siji-git slimbookbattery steam sxhkd system-config-printer tlp tlp-rdw tmux transmission-gtk unarchiver vlc vulkan-radeon wine wine-gecko wine-mono winetricks wireless_tools wmctrl wpa_supplicant xdg-user-dirs xdg-utils xf86-video-vesa xorg xsel xorg


yay -S acpilight bluetuith imlib pandoc-bin ponymix rsync siji-git slimbook-battery wpa_supplicant xdg-utils
